#
# config.yml
#
# Sample plugin configuration for the Synse IPMI Plugin. This
# plugin configuration is used for the example deployment and
# is configured to run against an IPMI simulator container.
#
# A different configuration YAML should be used for production
# deployments.
#
version: 1.0
debug: true
network:
  type: tcp
  address: ":5001"
settings:
  mode: parallel
  read:
    interval: 3s
  write:
    interval: 1s
dynamicRegistration:
  config:
    - hostname: ipmisim
      port: 623
      username: ADMIN
      password: ADMIN
      interface: lanplus
