#
# config.yml
#
# A basic plugin configuration for the Synse IPMI Plugin. This
# config is the default configuration file used in the Docker
# image for the plugin.
#
# With this configuration file, the plugin will not do anything,
# as there are no BMCs being configured. It is up to the user to
# supply their own configuration.
#
version: 1.0
name: ipmi

network:
  type: tcp
  address: ":5001"
