#
# Development Dockerfile
#
# This Dockerfile produces an image intended to only be used for
# development and debugging. It should NOT be used in production.
# Development images contain additional tooling that makes it easier
# to exec into a contain and dig into whatever may be going on inside.
#

FROM docker.io/vaporio/foundation:bionic

WORKDIR /synse

RUN apt-get update \
 && apt-get install -y --no-install-recommends ipmitool \
 && rm -rf /var/lib/apt/lists/*

# Copy the executable and README information. The executable should be
# built prior to the image build (see Makefile).
COPY synse-ipmi-plugin ./plugin
COPY README.md .

EXPOSE 5001
ENTRYPOINT ["./plugin"]
